---
- name: restart webserver
  service:
    name: "{{ apache_service }}"
    state: restarted

- name: start webserver
  service:
    name: "{{ apache_service }}"
    state: started
  notify: enable webserver

- name: enable webserver
  service:
    name: "{{ apache_service }}"
    state: enabled
  notify: restart webserver