---
- name: install composer
  shell: curl -sS https://getcomposer.org/installer | php

- name: move composer to /usr/local/bin
  shell: mv composer.phar /usr/local/bin/composer

- name: assign permissions to composer
  shell: chmod +x /usr/local/bin/composer

- include_tasks: clone_laravel.yml