---
  - name: start apache & enable on boot
    service:
      name: apache2
      state: started
      enabled: yes

  - name: start mariadb & enable on boot
    service:
      name: mariadb
      state: started
      enabled: yes

  - include_tasks: php_setup.yml