---
#Install Apache and dependencies for Debian/Ubuntu & RedHat/CentOS
- name: update cache
  apt: update_cache=yes
  when: ansible_os_family == 'Debian'

- name: Update for centos
  yum: update_cache=yes
  when: ansible_os_family == 'RedHat'

- name: Install required package
  package: 
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - wget
    - ufw
    - curl