---
#Add the necessary dependencies for PHP
- name: Install ca-certificates, apt-transport-https and software-properties-common
  package:
    name: "{{ item }}" 
    state: latest
  with_items:
    - ca-certificates
    - apt-transport-https
    - software-properties-common
  when: ansible_os_family == 'Debian'

#Add the GPG key for Debian/Ubuntu
- name: Add GPG key for Debian/Ubuntu
  apt_key:
    url: https://packages.sury.org/php/apt.gpg
    state: present
  when: ansible_os_family == 'Debian'

#Add sury repository for PHP on Debian/Ubuntu
- name: Add sury repository for PHP on Debian/Ubuntu
  apt_repository:
    repo: deb https://packages.sury.org/php/ {{ ansible_distribution_release }} main
    state: present
  when: ansible_os_family == 'Debian' and ansible_distribution_release in ['bullseye', 'buster', 'stretch', 'xenial', 'bionic', 'focal', 'bookworm']

#Update for debian
- name: Update for debian
  apt: update_cache=yes
  when: ansible_os_family == 'Debian'


  #Update for centos
- name: Update for centos
  yum: update_cache=yes
  when: ansible_os_family == 'RedHat'

#Install utils for CentOS
- name: Install epel-release yum-utils
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - epel-release
    - yum-utils
  when: ansible_os_family == 'RedHat'

#Install Remi repository for CentOS
- name: Install Remi repository for CentOS
  yum_repository:
    name: remi
    description: Remi PHP packages
    baseurl: http://rpms.remirepo.net/enterprise/{{ ansible_distribution_major_version }}/remi/$basearch/
    gpgcheck: yes
    gpgkey: https://rpms.remirepo.net/RPM-GPG-KEY-remi
    state: present
  when: ansible_os_family == 'RedHat'

#Install PHP and dependencies for CentOS
- name: Install PHP
  package:
    name: "{{ item }}"
    state: present
  with_items:
  - php
  - php-common
  - php-cli
  - php-mysqlnd
  - php-xml
  - php-mbstring
  - php-curl
  - php-fpm
  - php-mysqli
  - php-zip
  - php-gd
  - php-xmlrpc
  notify: restart webserver

