---
apache_packages: "{{ 'apache2' if ansible_os_family == 'Debian' else 'httpd'}}"
apache_service: "{{ 'apache2' if ansible_os_family == 'Debian' else 'httpd'}}"
apache_config_file: "{{ '/etc/httpd/conf.d/' if ansible_os_family == 'RedHat' else '/etc/apache2/sites-available/' }}"
project_url: "http://ekene.tech"
app_user: "www-data"
http_host: "ekene.tech"
http_conf: "{{ 'ekene.tech.conf' if ansible_os_family == 'Debian' else 'httpd.conf'}}"
http_port: "80"
admin_email: "broekeson@gmail.com"
project_name: "exam_project"
disable_default: true